apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 2 # set the number of replicas
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:   
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "gitea"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: gitea-secret
              key: postgres-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-secret
              key: postgres-password

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432 # not sure about this one
      targetPort: 5432