apiVersion: v1
kind: Secret
metadata:
  name: gitea-secret
type: Opaque
data:
  postgres-username: cG9zdGdyZXNfYWRtaW4=    # base64 for 'postgres'
  postgres-password: cG9zdGdyZXNfcGFzc3dvcmQ=    # base64 for 'SuperSecret'